spring:
  application:
    name: shopping-cart
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  instance:
    preferIpAddress: false
    instance-id: "${spring.application.name}:${random.value}"
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
